language: node_js
services:
  - mongodb
node_js:
  - "4.2"
before_script:
  - cp -a secrets.js.example secrets.js
script:
  - NODE_ENV=test node_modules/.bin/mocha --no-timeouts tests/models
  - NODE_ENV=test node_modules/.bin/mocha --no-timeouts tests/controllers.js
  - NODE_ENV=test node_modules/eslint/bin/eslint.js .
